---
apiVersion: v1
kind: Namespace
metadata:
  name: kysil-app
---

apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
  namespace: kysil-app
type: Opaque
data:
  MYSQL_DATABASE: c3BfNF9kYg==         # Base64 encoded "sp_4_db"
  MYSQL_USER: Zmxhc2stdXNlcg==         # Base64 encoded "flask-user"
  MYSQL_PASSWORD: Zmxhc2stcGFzc3dvcmQ= # Base64 encoded "flask-password"

---
apiVersion: v1
kind: Service
metadata:
  name: flask-sp-4
  namespace: kysil-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: flask-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-sp-4
  namespace: kysil-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: v2324/sp_4:1.0.100
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_APP
              value: "app.py"
            - name: DB_HOST
              value: "mysql-sp-4.kysil-mysql.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: MYSQL_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: MYSQL_DATABASE
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: