name: homework14

services:
  app:
    build:
      context: ./app
    image: ${COMPOSE_PROJECT_NAME}_app:1.0.1
    container_name: ${COMPOSE_PROJECT_NAME}_app
    hostname: ${COMPOSE_PROJECT_NAME}_app
    networks:
      _network:

  web:
    image: nginx:latest
    container_name: ${COMPOSE_PROJECT_NAME}_web_reverse_proxy
    hostname: ${COMPOSE_PROJECT_NAME}_web_reverse_proxy
    depends_on:
      - app
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      _network:

networks:
  _network:
