global:
  resolve_timeout: 5m

route:
  group_by: [ '...' ]
  receiver: 'telegram'
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 5m

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: "8082967971:AAHeteNipzDeKB05STNyPzrMYiPottFF2YQ"
        chat_id: -1001297550936
        message: '{{ template "telegram.default" . }}'

templates:
  - '/etc/alertmanager/templates/telegram.tmpl'
