groups:
  - name: 'Alert rules'
    rules:
      - alert: LowDiskSpace
        expr: (node_filesystem_free_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 15
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Низький рівень вільного місця"
          description: "Вільного місця залишилося менше 15%"

      - alert: HighCPUUsage
        expr: (100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Високе завантаження CPU"
          description: "ЦП завантажений більш ніж на 80%"

      - alert: TargetDown
        expr: up == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Екземпляр {{ $labels.job }} не працює"
          description: "{{ $labels.job }} не працює більше 2 хвилин"


